version: '3.8'

services:
  newsportal:  
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    environment:
      - DJANGO_SETTINGS_MODULE=NewsPortal.settings  
